12e8
Chain L              10        20        30        40        50        60        70        80        90       100       110       120       130       140       150       160       170       180       190       200       210
                      |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         |
   1 -  214  DIVMTQSQKFMSTSVGDRVSITCKASQNVGTAVAWYQQKPGQSPKLMIYSASNRYTGVPDRFTGSGSGTDFTLTISNMQSEDLADYFCQQYSSYPLTFGAGTKLELKRADAAPTVSIFPPSSEQLTSGGASVVCFLNNFYPKDINVKWKIDGSERQNGVLNSATDQDSKDSTYSMSSTLTLTKDEYERHNSYTCEATHKTSTSPIVKSFNRNEC
   1 -  214     SS   TSSSS TT  SSSSSSSTT  TT SSSSSS TTT  SSSSSTTTSS TT  TTSSSSSSTTSSSSSSTT  HHH TSSSSSS TTTT SS   SSSSS       SSSSS   HHHHTTTSSSSSSSSSSS TT  SSSSSSTTSS  TTSSSSS    TTT  SSSSSSSSSSHHHHTT TSSSSSSS TT TT SSSSSSTTT 
   1 -  214                           *** *         * **     ** **      **               *                            * **                                                           **                **           * **       *   
   1 -  214  A A A AAAAAA AAAAA   A A AAA  A       AAAA  A   A  AAAAAA AAA A AA  AA     AA AAA A         AA     A  A  AAAAA A A       AA AAAA         A   AA A A A AAAAAAAAAAA A A AAA     A      AAAA AAAA      A A  AAAAAAA AAAA 
Chain H              10        20        30        40        50         60        70        80           90       111100       110       120       130       140       150       160       170       180       190       200       210
                      |         |         |         |         |          |         |         |            |         ||||         |         |         |         |         |         |         |         |         |         |         |
 215 -  435  EVQLQQSGAEVVRSGASVKLSCTASGFNIKDYYIHWVKQRPEKGLEWIGWIDPEIGDTEYVPKFQGKATMTADTSSNTAYLQLSSLTSEDTAVYYCNAGHDYDRGRFPYWGQGTLVTVSAAKTTPPSVYPLAPGSAAQTNSMVTLGCLVKGYFPEPVTVTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVPSSTWPSETVTCNVAHPASSTKVDKKIVPRD
 215 -  435    SSSS   SSSSTT  SSSSSSSSTT HHHSSSSSSSS TTT SSSSSSS TTT  SSS HHH TTSSSSSSTTTTSSSSSS T  HHH SSSSSSSSSTTTTT   SS   SSSSSS       SSSSS      T  TTSSSSSSSSSS TT  SSSSHHHT  TTSSS   SSSTTSSSSSSSSSS HHHTTTT  SSSSSSHHHTSSSSSS  T  
 215 -  435    * ** *    ***               * *                  *****     *         ***          ***             **** *     *            *                *             * * *                              *     *         *  *******     
 215 -  435  AAA A  AAAA AAA A A   A AA A AA A     AAAAA      A   AAAAAAA AA AAA A A AAAA   A   AA AAA   A      AAA A A        A    A AAAA A     AA      AA       A    AA A A AAAAAAAAA A A  AAAAA       A AAAA AAAA       AA AAAAA A AAAA
Chain M              10        20        30        40        50        60        70        80        90       100       110       120       130       140       150       160       170       180       190       200       210
                      |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         |         |
 436 -  649  DIVMTQSQKFMSTSVGDRVSITCKASQNVGTAVAWYQQKPGQSPKLMIYSASNRYTGVPDRFTGSGSGTDFTLTISNMQSEDLADYFCQQYSSYPLTFGAGTKLELKRADAAPTVSIFPPSSEQLTSGGASVVCFLNNFYPKDINVKWKIDGSERQNGVLNSATDQDSKDSTYSMSSTLTLTKDEYERHNSYTCEATHKTSTSPIVKSFNRNEC
 436 -  649     SS   TSSSS TT  SSSSSSSTT  TT SSSSSS TTT  SSSSSTTTSS TT  TTSSSSSSTTSSSSSSTT  HHH TSSSSSS TTTT SS   SSSSS       SSSSS   HHHHTTTSSSSSSSSSSS TT  SSSSSSTTSSS TTSSSSS    TTT  SSSSSSSSSSHHHHTT TSSSSSSSSTTSSSSSSSSSSHHH 
 436 -  649  *                        *** **                 ** ***  * **      *            *                                         **                       *      * **                              * *        * **         *  
 436 -  649  A A A AAAAAA  A  A A A A AAA AA       AAAA  A   A  AAAAAA AAA A AAA AA     AA AAA A        AAA     A  A  AAAAA A A       AA  AAA         A   AA A A A AAAAAAAA AA A A AAA     A      AAA  AA A      A A AAAAAAAA AAAAA
Chain P              10        20        30        40        50         60        70        80           90       111100       110       120       130       140       150       160       170       180       190       200       210
                      |         |         |         |         |          |         |         |            |         ||||         |         |         |         |         |         |         |         |         |         |         |
 650 -  870  EVQLQQSGAEVVRSGASVKLSCTASGFNIKDYYIHWVKQRPEKGLEWIGWIDPEIGDTEYVPKFQGKATMTADTSSNTAYLQLSSLTSEDTAVYYCNAGHDYDRGRFPYWGQGTLVTVSAAKTTPPSVYPLAPGSAAQTNSMVTLGCLVKGYFPEPVTVTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVPSSTWPSETVTCNVAHPASSTKVDKKIVPRD
 650 -  870    SSSS   SSSSTT  SSSSSSSSTT HHHSSSSSSSSSTTSSSSSSSSS TTT  SSS HHHTTTSSSSSSTTTTSSSSSS T  HHH SSSSSSSSSTTTTT  TSS   SSSSSST      SSSSS   T   T TSSSSSSSSSSS TT  SSSSHHHT  TTSSS   SSSTTSSSSSSSSSSSTTTTTTT  SSSSSSHHHTSSSSSS  T  
 650 -  870              **                * *                     * *    *  **                 **               ** * *                                                         ** **                                         ******* *   
 650 -  870  AAA A AAAAA AAA A A   A AA A AA A     AAAAA          AAAAAAA AA AAA A A AAAA   A A AA AAA A A      AAA A A  A  A  A    A AAAA A     AA      AA       A    AA A A AA A AAAA A A  AAAAA       A AAA  AAAA       AA AAAAAAA AAA 
*END
